# Generated by Django 6.0.1 on 2026-01-31 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_api', '0002_increase_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('avg_entry_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('current_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unrealized_pl', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unrealized_plpc', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'position_snapshots',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='trade',
            name='filled_avg_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='filled_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='limit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('filled', 'Filled'), ('executed', 'Executed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('inactive', 'Inactive')], default='executed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['order_id'], name='trades_order_i_836d39_idx'),
        ),
        migrations.AddField(
            model_name='positionsnapshot',
            name='portfolio_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='trading_api.portfoliosnapshot'),
        ),
        migrations.AddField(
            model_name='positionsnapshot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='positionsnapshot',
            index=models.Index(fields=['symbol', 'timestamp'], name='position_sn_symbol_ac720c_idx'),
        ),
    ]
