# Generated by Django 6.0.1 on 2026-02-15 02:30

import trading_api.models.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_api', '0006_merge_0004_watchlistitem_0005_agentrunlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', max_length=32, unique=True)),
                ('analysis_interval_minutes', models.IntegerField(default=15)),
                ('max_position_pct', models.FloatField(default=0.1)),
                ('max_daily_loss_pct', models.FloatField(default=0.03)),
                ('min_confidence', models.FloatField(default=0.7)),
                ('stop_loss_pct', models.FloatField(default=0.05)),
                ('take_profit_pct', models.FloatField(default=0.1)),
                ('indicator_settings', models.JSONField(blank=True, default=trading_api.models.settings.default_indicator_settings)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agent_settings',
            },
        ),
    ]
