# Generated by Django 6.0.1 on 2026-02-17 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_api', '0007_agentsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('access_token', models.TextField()),
                ('institution_id', models.CharField(blank=True, default='', max_length=128)),
                ('institution_name', models.CharField(blank=True, default='', max_length=255)),
                ('product_type', models.CharField(choices=[('investments', 'Investments'), ('bank', 'Bank')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('login_required', 'Login Required'), ('error', 'Error'), ('disconnected', 'Disconnected')], db_index=True, default='active', max_length=32)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('consent_expiration_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaid_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plaid_items',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaidAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('official_name', models.CharField(blank=True, default='', max_length=255)),
                ('mask', models.CharField(blank=True, default='', max_length=16)),
                ('account_type', models.CharField(blank=True, default='', max_length=64)),
                ('subtype', models.CharField(blank=True, default='', max_length=64)),
                ('verification_status', models.CharField(blank=True, default='', max_length=64)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('available_balance', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('limit_balance', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('iso_currency_code', models.CharField(blank=True, default='', max_length=8)),
                ('unofficial_currency_code', models.CharField(blank=True, default='', max_length=16)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='trading_api.plaiditem')),
            ],
            options={
                'db_table': 'plaid_accounts',
                'ordering': ['name', 'account_id'],
            },
        ),
        migrations.CreateModel(
            name='PlaidSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_id', models.CharField(db_index=True, max_length=128)),
                ('ticker_symbol', models.CharField(blank=True, default='', max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('security_type', models.CharField(blank=True, default='', max_length=64)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('close_price_as_of', models.DateField(blank=True, null=True)),
                ('iso_currency_code', models.CharField(blank=True, default='', max_length=8)),
                ('unofficial_currency_code', models.CharField(blank=True, default='', max_length=16)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities', to='trading_api.plaiditem')),
            ],
            options={
                'db_table': 'plaid_securities',
                'ordering': ['ticker_symbol', 'security_id'],
            },
        ),
        migrations.CreateModel(
            name='PlaidInvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_transaction_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('ticker_symbol', models.CharField(blank=True, default='', max_length=32)),
                ('tx_type', models.CharField(blank=True, default='', max_length=64)),
                ('subtype', models.CharField(blank=True, default='', max_length=64)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('cancel_transaction_id', models.CharField(blank=True, default='', max_length=128)),
                ('iso_currency_code', models.CharField(blank=True, default='', max_length=8)),
                ('unofficial_currency_code', models.CharField(blank=True, default='', max_length=16)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_transactions', to='trading_api.plaidaccount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_transactions', to='trading_api.plaiditem')),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_transactions', to='trading_api.plaidsecurity')),
            ],
            options={
                'db_table': 'plaid_investment_transactions',
                'ordering': ['-date', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaidHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('institution_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('institution_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('cost_basis', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('iso_currency_code', models.CharField(blank=True, default='', max_length=8)),
                ('unofficial_currency_code', models.CharField(blank=True, default='', max_length=16)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='trading_api.plaidaccount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='trading_api.plaiditem')),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holdings', to='trading_api.plaidsecurity')),
            ],
            options={
                'db_table': 'plaid_holdings',
                'ordering': ['-institution_value', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlaidSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], db_index=True, max_length=32)),
                ('message', models.TextField(blank=True, default='')),
                ('accounts_synced', models.IntegerField(default=0)),
                ('holdings_synced', models.IntegerField(default=0)),
                ('transactions_synced', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='trading_api.plaiditem')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaid_sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plaid_sync_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='plaiditem',
            index=models.Index(fields=['user', 'product_type'], name='plaid_items_user_id_b061d0_idx'),
        ),
        migrations.AddIndex(
            model_name='plaiditem',
            index=models.Index(fields=['user', 'status'], name='plaid_items_user_id_50095c_idx'),
        ),
        migrations.AddIndex(
            model_name='plaidaccount',
            index=models.Index(fields=['item', 'account_type'], name='plaid_accou_item_id_8fdda4_idx'),
        ),
        migrations.AddConstraint(
            model_name='plaidsecurity',
            constraint=models.UniqueConstraint(fields=('item', 'security_id'), name='plaid_security_item_unique'),
        ),
        migrations.AddIndex(
            model_name='plaidinvestmenttransaction',
            index=models.Index(fields=['item', 'date'], name='plaid_inves_item_id_786193_idx'),
        ),
        migrations.AddConstraint(
            model_name='plaidholding',
            constraint=models.UniqueConstraint(fields=('item', 'account', 'security'), name='plaid_holding_unique'),
        ),
        migrations.AddIndex(
            model_name='plaidsynclog',
            index=models.Index(fields=['status', 'started_at'], name='plaid_sync__status_0920f8_idx'),
        ),
    ]
